---
title: "About Me"
author: "Jacob Hoang"
subtitle: "\"If the only tool you have is a hammer, you tend to see every problem as a nail.\" - Abraham Maslow"
date: 2023-07-25T21:13:14-05:00
categories: ["R"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Professional Summary

I am a results-oriented process engineering and project management professional turned data scientist with over 10 years of experience who is skilled in statistical techniques, continuous improvement, big data analytics, and New Product Introduction/Transfer (NPI) in a high-volume manufacturing environment. I have a proven track record of contributing to complex objectives and building effective teams where I was known for strong leadership, consensus building, personal growth, and accountability. At Illumina, I played a critical role in 6 platform launches.

## Resume

For a brief background of my previous roles, please see my [LinkedIn](https://www.linkedin.com/in/jacobnhoang/) profile.

---

## Website Background

The purpose of this website is to demonstrate my abilities in data science, analytics, and engineering. Since I have the most technical experience in R, I thought it would be a fun challenge to build this website using the R [blogdown](https://bookdown.org/yihui/blogdown/) package. The theme I leveraged is the [Beautiful Hugo](https://themes.gohugo.io/themes/beautifulhugo/) theme. As the quote mentions, R is currently my hammer, and these challenges I'm taking on are the nails! With that said, I will likely replicate some of these challenges using Python and SQL/T-SQL to demonstrate my skills.